/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    machines: Machine;
    attachments: Attachment;
    lubricants: Lubricant;
    parts: Part;
    posts: Post;
    addons: Addon;
    warranties: Warranty;
    'finance-promos': FinancePromo;
    categories: Category;
    media: Media;
    documents: Document;
    leads: Lead;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    machines: MachinesSelect<false> | MachinesSelect<true>;
    attachments: AttachmentsSelect<false> | AttachmentsSelect<true>;
    lubricants: LubricantsSelect<false> | LubricantsSelect<true>;
    parts: PartsSelect<false> | PartsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    addons: AddonsSelect<false> | AddonsSelect<true>;
    warranties: WarrantiesSelect<false> | WarrantiesSelect<true>;
    'finance-promos': FinancePromosSelect<false> | FinancePromosSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    financing: Financing;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    financing: FinancingSelect<false> | FinancingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machines".
 */
export interface Machine {
  id: number;
  modelName: string;
  brand: string;
  /**
   * e.g. PRO Series
   */
  series?: string | null;
  category: 'excavators' | 'skid-steers' | 'loaders' | 'track-dumpers';
  /**
   * Short label like 'Most Popular' or 'New'.
   */
  badge?: string | null;
  /**
   * 1–2 sentences for cards.
   */
  shortDescription: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. 2 year warranty
   */
  warranty?: string | null;
  /**
   * Badges shown in the hero, e.g. EPA Tier 4 Final, CE.
   */
  certifications?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * First image is the main photo.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        label: string;
        file: number | Document;
        id?: string | null;
      }[]
    | null;
  /**
   * Big image + headline blocks, e.g. 'Powerful Performance' / 'Explosion-proof valve'.
   */
  features?:
    | {
        /**
         * Small label, e.g. 'Engineered performance'
         */
        eyebrow?: string | null;
        title: string;
        text: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  standardEquipment?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  applications?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. Homeowners and small farm owners
   */
  targetUsers?: string | null;
  /**
   * e.g. Ultra-quiet
   */
  noiseLevel?: string | null;
  /**
   * Suitable for indoor use.
   */
  indoorUse?: boolean | null;
  /**
   * Attachment mounting standard (skid steers / loaders).
   */
  plateType?: ('toro-dingo' | 'rippa-mini' | 'universal-ssl' | 'excavator-qc' | 'pin-on') | null;
  /**
   * Shown under the attachments list, e.g. plate conversion offer. Leave blank for the default wording.
   */
  plateNote?: string | null;
  /**
   * Rate how well this model handles each job and which attachments it needs.
   */
  applicationFit?:
    | {
        application: string;
        rating: '4' | '3' | '2' | '1' | '0';
        /**
         * Required attachments
         */
        attachments?: string | null;
        id?: string | null;
      }[]
    | null;
  checklist?:
    | {
        group: 'safety' | 'comfort' | 'other';
        feature: string;
        status: 'standard' | 'optional' | 'na';
        /**
         * e.g. Heating & cooling
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Full spec table. Mark 3–5 as highlights to show on cards and in the hero stats. Add an imperial value to enable the metric / imperial toggle.
   */
  specs?:
    | {
        label: string;
        /**
         * Metric
         */
        value: string;
        imperial?: string | null;
        group?: ('general' | 'performance' | 'engine' | 'dimensions') | null;
        icon?:
          ('weight' | 'engine' | 'depth' | 'warranty' | 'power' | 'capacity' | 'width' | 'reach' | 'generic') | null;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Untick to show 'Request pricing' everywhere.
   */
  showPrice?: boolean | null;
  /**
   * Engine / cab / undercarriage options. The lowest price becomes the 'Starting from' price.
   */
  configurations?:
    | {
        label: string;
        engine?: string | null;
        horsepower?: string | null;
        operatingWeight?: string | null;
        /**
         * CAD
         */
        price?: number | null;
        sku?: string | null;
        inStock?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * CAD. Used only when there are no configurations.
   */
  basePrice?: number | null;
  /**
   * CAD. Overrides base price when set.
   */
  promoPrice?: number | null;
  /**
   * Show in the Excavator Builder (excavators only).
   */
  builderEnabled?: boolean | null;
  /**
   * URL path segment, e.g. r15-5-eco. Auto-filled from the name when empty.
   */
  slug: string;
  /**
   * Show on homepage / featured rows.
   */
  featured?: boolean | null;
  inStock?: ('unknown' | 'in-stock' | 'order') | null;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Product photos and site images. Use cut-outs on white/transparent backgrounds so buckets and attachments are never cropped.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the product in the photo, e.g. 'RIPPA R15-5 ECO mini excavator, canopy'.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Downloadable spec sheets, brochures and manuals (PDF).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  kind?: ('spec-sheet' | 'brochure' | 'manual' | 'other') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attachments".
 */
export interface Attachment {
  id: number;
  name: string;
  /**
   * Grouping label: Bucket, Thumb, Auger, Forks…
   */
  attachmentType: string;
  attachmentCategory: 'excavator-attachments' | 'skid-steer-attachments' | 'loader-attachments';
  /**
   * Short line for cards, e.g. '12" – 24" options'.
   */
  description: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * First image is the main photo.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        label: string;
        file: number | Document;
        id?: string | null;
      }[]
    | null;
  /**
   * Fits every machine in these categories (used when no specific models are listed).
   */
  compatibleCategories?: ('excavators' | 'skid-steers' | 'loaders' | 'track-dumpers')[] | null;
  /**
   * Fits only these models. Leave empty to use categories.
   */
  compatibleModels?: (number | Machine)[] | null;
  /**
   * Mounting standard this attachment ships with. -1 mini loader attachments = Toro Dingo style; -2 / -3 = RIPPA proprietary plate.
   */
  plateType?: ('toro-dingo' | 'rippa-mini' | 'universal-ssl' | 'excavator-qc' | 'pin-on') | null;
  /**
   * Manufacturer catalogue page.
   */
  sourceUrl?: string | null;
  showPrice?: boolean | null;
  /**
   * CAD. Used when there are no variants.
   */
  basePrice?: number | null;
  /**
   * Allow quantity > 1 (teeth, tracks, etc.).
   */
  supportsQuantity?: boolean | null;
  /**
   * Sizes / widths with their own price. Optionally restrict a variant to specific models.
   */
  variants?:
    | {
        label: string;
        widthOrSize?: string | null;
        sku?: string | null;
        price?: number | null;
        compatibleModels?: (number | Machine)[] | null;
        /**
         * Mounting plate this version ships with, when it differs by version (RS -1 vs -2/-3).
         */
        plateType?: ('toro-dingo' | 'rippa-mini' | 'universal-ssl' | 'excavator-qc' | 'pin-on') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL path segment, e.g. r15-5-eco. Auto-filled from the name when empty.
   */
  slug: string;
  /**
   * Show on homepage / featured rows.
   */
  featured?: boolean | null;
  inStock?: ('unknown' | 'in-stock' | 'order') | null;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lubricants".
 */
export interface Lubricant {
  id: number;
  /**
   * e.g. DURON UHP
   */
  name: string;
  brand?: string | null;
  category:
    'engine-oil' | 'hydraulic' | 'gear' | 'transmission' | 'grease' | 'coolant' | 'def' | 'food-grade' | 'other';
  /**
   * One line, e.g. 'Heavy-duty diesel engine oil for extended drains'.
   */
  tagline?: string | null;
  description: string;
  /**
   * Viscosity grades / variants, e.g. 5W-40, 10W-30, 15W-40
   */
  grades?: string | null;
  applications?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  packaging?: ('1l' | '4l' | '20l' | 'drum' | 'tote' | 'bulk' | 'cartridge')[] | null;
  /**
   * OEM / API approvals to list, e.g. API CK-4, Kubota approved
   */
  approvals?: string | null;
  /**
   * Where it's used on RIPPA machines, e.g. 'Engine oil for Kubota D722 / D902 / V1505'.
   */
  rippaUse?: string | null;
  /**
   * First image is the main photo.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        label: string;
        file: number | Document;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  /**
   * URL path segment, e.g. r15-5-eco. Auto-filled from the name when empty.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parts".
 */
export interface Part {
  id: number;
  name: string;
  /**
   * RIPPA part number, e.g. LP0101010001
   */
  sku: string;
  system:
    | 'filters'
    | 'engine'
    | 'fuel-system'
    | 'hydraulic-system'
    | 'hydraulic-cylinders'
    | 'hydraulic-components'
    | 'electrical'
    | 'undercarriage'
    | 'traction'
    | 'body'
    | 'work-equipment'
    | 'canopy'
    | 'controls'
    | 'decals'
    | 'accessories'
    | 'other';
  /**
   * For engine parts only.
   */
  engineBrand?: ('kubota' | 'briggs-stratton') | null;
  /**
   * Machines this part is listed for.
   */
  compatibleModels?: (number | Machine)[] | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * rippagroup.ca product page
   */
  sourceUrl?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  /**
   * URL path segment, e.g. r15-5-eco. Auto-filled from the name when empty.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  category: 'guide' | 'field-call' | 'maintenance' | 'buying' | 'attachments' | 'parts' | 'lubricants' | 'news';
  publishedAt: string;
  /**
   * 1–2 sentences shown on cards and in search results.
   */
  excerpt: string;
  cover?: (number | null) | Media;
  /**
   * YouTube watch/short URL. Embedded at the top of the post.
   */
  videoUrl?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown as 'Applies to' chips and links the post from those product pages.
   */
  relatedMachines?: (number | Machine)[] | null;
  relatedAttachments?: (number | Attachment)[] | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Estimated reading time.
   */
  readMinutes?: number | null;
  featured?: boolean | null;
  author?: string | null;
  /**
   * URL path segment, e.g. r15-5-eco. Auto-filled from the name when empty.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons".
 */
export interface Addon {
  id: number;
  name: string;
  type: 'protection' | 'pdi' | 'delivery' | 'service';
  icon?: ('shield' | 'wrench' | 'truck' | 'file') | null;
  shortDescription: string;
  fullDescription?: string | null;
  /**
   * CAD. Leave blank if quoted.
   */
  price?: number | null;
  quoteRequired?: boolean | null;
  /**
   * Eligible for every builder model.
   */
  allModels?: boolean | null;
  compatibleModels?: (number | Machine)[] | null;
  selectable?: boolean | null;
  defaultSelected?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warranties".
 */
export interface Warranty {
  id: number;
  name: string;
  termMonths: number;
  /**
   * CAD
   */
  price?: number | null;
  financeEligible?: boolean | null;
  coverageSummary: string;
  allModels?: boolean | null;
  eligibleModels?: (number | Machine)[] | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-promos".
 */
export interface FinancePromo {
  id: number;
  /**
   * e.g. 0% financing on R15-5 ECO
   */
  title: string;
  kind: 'promo' | 'program';
  /**
   * Short label shown on cards and product pages, e.g. '0% APR' or 'No payments 90 days'.
   */
  badge?: string | null;
  /**
   * One or two sentences.
   */
  summary: string;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * OAC wording, term limits, expiry, exclusions.
   */
  terms?: string | null;
  startDate?: string | null;
  /**
   * Promo hides automatically after this date.
   */
  endDate?: string | null;
  /**
   * Applies to every machine.
   */
  allModels?: boolean | null;
  /**
   * Models this offer applies to (listed on the promo card).
   */
  eligibleModels?: (number | Machine)[] | null;
  ctaLabel?: string | null;
  /**
   * #apply scrolls to the form; or paste a LeaseLink application URL.
   */
  ctaHref?: string | null;
  active?: boolean | null;
  /**
   * Also show as a strip under the homepage hero.
   */
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Names, descriptions and images for the category pages and menus.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  kind: 'machine' | 'attachment';
  slug:
    | 'excavators'
    | 'skid-steers'
    | 'loaders'
    | 'track-dumpers'
    | 'excavator-attachments'
    | 'skid-steer-attachments'
    | 'loader-attachments';
  name: string;
  /**
   * Used on tiles and menus.
   */
  shortName?: string | null;
  description: string;
  image?: (number | null) | Media;
  sortOrder?: number | null;
  /**
   * Longer introduction shown under the model grid.
   */
  intro?: string | null;
  buyingGuide?:
    | {
        /**
         * e.g. Homeowners & backyard projects
         */
        title: string;
        text: string;
        models?: (number | Machine)[] | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  title: string;
  source: 'quote' | 'builder' | 'contact' | 'financing' | 'service' | 'parts' | 'lubricants' | 'content-request';
  status?: ('new' | 'synced' | 'failed' | 'handled') | null;
  name: string;
  email: string;
  phone: string;
  company?: string | null;
  location?: string | null;
  message?: string | null;
  lines?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Page the form was sent from.
   */
  page?: string | null;
  ghlContactId?: string | null;
  ghlOpportunityId?: string | null;
  error?: string | null;
  /**
   * Raw submission.
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'machines';
        value: number | Machine;
      } | null)
    | ({
        relationTo: 'attachments';
        value: number | Attachment;
      } | null)
    | ({
        relationTo: 'lubricants';
        value: number | Lubricant;
      } | null)
    | ({
        relationTo: 'parts';
        value: number | Part;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'addons';
        value: number | Addon;
      } | null)
    | ({
        relationTo: 'warranties';
        value: number | Warranty;
      } | null)
    | ({
        relationTo: 'finance-promos';
        value: number | FinancePromo;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machines_select".
 */
export interface MachinesSelect<T extends boolean = true> {
  modelName?: T;
  brand?: T;
  series?: T;
  category?: T;
  badge?: T;
  shortDescription?: T;
  longDescription?: T;
  warranty?: T;
  certifications?:
    | T
    | {
        text?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  features?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        image?: T;
        id?: T;
      };
  standardEquipment?:
    | T
    | {
        text?: T;
        id?: T;
      };
  applications?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  targetUsers?: T;
  noiseLevel?: T;
  indoorUse?: T;
  plateType?: T;
  plateNote?: T;
  applicationFit?:
    | T
    | {
        application?: T;
        rating?: T;
        attachments?: T;
        id?: T;
      };
  checklist?:
    | T
    | {
        group?: T;
        feature?: T;
        status?: T;
        note?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        imperial?: T;
        group?: T;
        icon?: T;
        highlight?: T;
        id?: T;
      };
  showPrice?: T;
  configurations?:
    | T
    | {
        label?: T;
        engine?: T;
        horsepower?: T;
        operatingWeight?: T;
        price?: T;
        sku?: T;
        inStock?: T;
        id?: T;
      };
  basePrice?: T;
  promoPrice?: T;
  builderEnabled?: T;
  slug?: T;
  featured?: T;
  inStock?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attachments_select".
 */
export interface AttachmentsSelect<T extends boolean = true> {
  name?: T;
  attachmentType?: T;
  attachmentCategory?: T;
  description?: T;
  longDescription?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  compatibleCategories?: T;
  compatibleModels?: T;
  plateType?: T;
  sourceUrl?: T;
  showPrice?: T;
  basePrice?: T;
  supportsQuantity?: T;
  variants?:
    | T
    | {
        label?: T;
        widthOrSize?: T;
        sku?: T;
        price?: T;
        compatibleModels?: T;
        plateType?: T;
        id?: T;
      };
  slug?: T;
  featured?: T;
  inStock?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lubricants_select".
 */
export interface LubricantsSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  category?: T;
  tagline?: T;
  description?: T;
  grades?: T;
  applications?:
    | T
    | {
        text?: T;
        id?: T;
      };
  packaging?: T;
  approvals?: T;
  rippaUse?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  featured?: T;
  sortOrder?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parts_select".
 */
export interface PartsSelect<T extends boolean = true> {
  name?: T;
  sku?: T;
  system?: T;
  engineBrand?: T;
  compatibleModels?: T;
  description?: T;
  image?: T;
  sourceUrl?: T;
  featured?: T;
  sortOrder?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  publishedAt?: T;
  excerpt?: T;
  cover?: T;
  videoUrl?: T;
  content?: T;
  relatedMachines?: T;
  relatedAttachments?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  readMinutes?: T;
  featured?: T;
  author?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons_select".
 */
export interface AddonsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  icon?: T;
  shortDescription?: T;
  fullDescription?: T;
  price?: T;
  quoteRequired?: T;
  allModels?: T;
  compatibleModels?: T;
  selectable?: T;
  defaultSelected?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warranties_select".
 */
export interface WarrantiesSelect<T extends boolean = true> {
  name?: T;
  termMonths?: T;
  price?: T;
  financeEligible?: T;
  coverageSummary?: T;
  allModels?: T;
  eligibleModels?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-promos_select".
 */
export interface FinancePromosSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  badge?: T;
  summary?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  terms?: T;
  startDate?: T;
  endDate?: T;
  allModels?: T;
  eligibleModels?: T;
  ctaLabel?: T;
  ctaHref?: T;
  active?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  kind?: T;
  slug?: T;
  name?: T;
  shortName?: T;
  description?: T;
  image?: T;
  sortOrder?: T;
  intro?: T;
  buyingGuide?:
    | T
    | {
        title?: T;
        text?: T;
        models?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  title?: T;
  source?: T;
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  location?: T;
  message?: T;
  lines?:
    | T
    | {
        text?: T;
        id?: T;
      };
  page?: T;
  ghlContactId?: T;
  ghlOpportunityId?: T;
  error?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Display format, e.g. (905) 555-0123
   */
  phone?: string | null;
  email?: string | null;
  street?: string | null;
  city?: string | null;
  postal?: string | null;
  serviceArea?: string | null;
  hours?:
    | {
        day: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  announcementLeft?: string | null;
  announcementRight?: string | null;
  /**
   * Full profile URLs. Handles are shown on the blog and footer.
   */
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
    tiktok?: string | null;
    /**
     * e.g. @niagaraequipment
     */
    instagramHandle?: string | null;
    youtubeHandle?: string | null;
    facebookHandle?: string | null;
    tiktokHandle?: string | null;
  };
  /**
   * Google Maps embed URL (Share → Embed a map → copy the src).
   */
  mapEmbedUrl?: string | null;
  /**
   * Builder estimate tax, e.g. 13 for 13% HST. Leave blank to hide the tax line.
   */
  taxRate?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Monthly payment examples only appear when 'Show estimates' is on and a rate + term are set.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing".
 */
export interface Financing {
  id: number;
  showEstimates?: boolean | null;
  /**
   * % APR
   */
  annualRate?: number | null;
  termMonths?: number | null;
  downPaymentPercent?: number | null;
  /**
   * Financing partner shown on the Financing page.
   */
  partnerName?: string | null;
  partnerUrl?: string | null;
  /**
   * Direct online application link, if the partner provides one.
   */
  partnerApplyUrl?: string | null;
  /**
   * One paragraph about the partner and what they finance.
   */
  partnerBlurb?: string | null;
  disclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  street?: T;
  city?: T;
  postal?: T;
  serviceArea?: T;
  hours?:
    | T
    | {
        day?: T;
        time?: T;
        id?: T;
      };
  announcementLeft?: T;
  announcementRight?: T;
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        linkedin?: T;
        tiktok?: T;
        instagramHandle?: T;
        youtubeHandle?: T;
        facebookHandle?: T;
        tiktokHandle?: T;
      };
  mapEmbedUrl?: T;
  taxRate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing_select".
 */
export interface FinancingSelect<T extends boolean = true> {
  showEstimates?: T;
  annualRate?: T;
  termMonths?: T;
  downPaymentPercent?: T;
  partnerName?: T;
  partnerUrl?: T;
  partnerApplyUrl?: T;
  partnerBlurb?: T;
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}